port: 4000
# Site settings
baseurl: "http://cortega8612.github.io/expmaq"
title: Expansion Maquinados Industriales
description: Expansion en Maquinados Industriales
email: your-email@domain.com

# Build settings
markdown: kramdown

