port: 4000
# Site settings
title: Expansion Maquinados Industriales
description: Expansion en Maquinados Industriales
email: your-email@domain.com

# Build settings
markdown: kramdown

gems:
  - jekyll-sitemap